export default {
  SPLASH: 'SPLASH',

  LOGIN: 'Đăng nhập',
  REGISTER: 'Đăng ký',
  FORGOT_PASSWORD: 'Quên mật khẩu',

  HOME_NAV: 'MEGOO',
  HOME: 'Trang chủ',
  HOME_DRAWER: 'HOME_DRAWER',
  HOME_STACK_DRAWER: 'HOME_STACK_DRAWER',
  HOME_STACK_BOTTOM: 'HOME_STACK_BOTTOM',

  GROUP_BILL_LIST: 'Danh sách nhóm',
  BILL_LIST_STACK: 'BILL__LIST_STACK',
  BILL_STACK: 'BILL_STACK',
  BILL_MANAGEMENT: 'Quản lý chi tiêu',
  BILL: 'Phân chia chi tiêu',
  BILL_INFO: 'Thông tin chi tiết',

  GROUP_TODOS_LIST: 'Danh sách nhóm',
  TODOS_LIST_STACK: 'TODOS_LIST_STACK',
  TODOS_TAB: 'Quản lý công việc',
  TODOS_LIST: 'Danh sách công việc',
  CREATE_TODOS: 'Tạo công việc',
  TODOS: 'Việc cần làm',

  GROUP_TASK_LIST: 'Danh sách nhóm',
  TASK_LIST_STACK: 'TASK_LIST_STACK',
  TASK_LIST: 'Quản lý thời gian',
  TASK: 'Lịch biểu',
  CREATE_TASK: 'Tạo sự kiện',

  PACKAGE_STACK_DRAWER: 'PACKAGE_STACK_DRAWER',
  PACKAGE_STACK_BOTTOM: 'PACKAGE_STACK_BOTTOM',
  PACKAGE: 'Quản lý gói',
  CURRENT_PACKAGE: 'Gói hiện tại',
  OTHER_PACKAGES: 'Các gói khác',
  CART: 'Giỏ hàng',

  GROUPS: 'Danh sách nhóm',
  GROUP_INFO: 'Thông tin chi tiết',

  PAYMENT: 'Thanh toán',

  STORAGE_STACK_DRAWER: 'STORAGE_STACK_DRAWER',
  STORAGE_STACK_BOTTOM: 'STORAGE_STACK_BOTTOM',
  STORAGE_GROUPS: 'Danh sách nhóm',
  STORAGE: 'Quản lý kho',
  PRODUCTS: 'Danh sách sản phẩm nhu yếu phẩm',
  PRODUCT_DETAIL: 'Chi tiết sản phẩm nhu yếu phẩm',
  ADD_PRODUCT_INFO: 'Thêm sản phẩm nhu yếu phẩm',
  ADD_GROUP_PRODUCT: 'Thêm loại nhu yếu phẩm',
  ADD_STORAGE_LOCATION: 'Thêm vị trí lưu trữ',
  ADD_PURCHASE_LOCATION: 'Thêm vị trí mua sắm',
  SCAN_BARCODE: 'Quét barcode',

  TOP_TAB: 'TOP_TAB',
  PROFILE_TOP_TAB: 'PROFILE_TOP_TAB',
  GROUP_STACK: 'GROUP_TOP_TAB',
  PROFILE_STACK: 'PROFILE_STACK',
  PROFILE: 'Trang cá nhân',
  EDIT_PROFILE: 'Chỉnh sửa thông tin cá nhân',
  EDIT_GROUP_INFO: 'Chỉnh sửa thông tin nhóm',
  CHANGE_AVATAR: 'Chỉnh sửa ảnh đại diện',

  SETTINGS_STACK_DRAWER: 'SETTINGS_STACK_DRAWER',
  SETTINGS_STACK_BOTTOM: 'SETTINGS_STACK_BOTTOM',
  SETTINGS: 'Cài đặt',
  APP_INFO: 'Thông tin ứng dụng',
  POLICIES_RIGHTS: 'Chính sách và quyền',

  CHAT_STACK: 'CHAT_STACK',
  CHAT: 'Đoạn chat',
  GROUP_CHATS: 'Nhóm chat',
};
